last_change = 2025-10-28T01:57:08.272140Z
addr = 0x219650
size = 0x3
name = "??1?$Flag@I@fw@@QEAI@XZ"
type = "void"

[header]
name = "??1?$Flag@I@fw@@QEAI@XZ"
addr = 0x219650
type = "void"

[header.args]
