last_change = 2025-10-28T01:57:08.272640Z
addr = 0x4aad70
size = 0xd6
name = "??$make_shared_with_deleter@VStatusMenuClassDetailChoice_Data@ope@ui@app@@@TPL@@YIV?$shared_ptr@VStatusMenuClassDetailChoice_Data@ope@ui@app@@U?$deleter_for_shared_ptr@VStatusMenuClassDetailChoice_Data@ope@ui@app@@@TPL@@@std@@XZ"
type = "void *"

[header]
name = "??$make_shared_with_deleter@VStatusMenuClassDetailChoice_Data@ope@ui@app@@@TPL@@YIV?$shared_ptr@VStatusMenuClassDetailChoice_Data@ope@ui@app@@U?$deleter_for_shared_ptr@VStatusMenuClassDetailChoice_Data@ope@ui@app@@@TPL@@@std@@XZ"
addr = 0x4aad70
type = "void *"

[header.args]
