last_change = 2025-10-28T01:57:08.272640Z
addr = 0x4b2010
size = 0xd4
name = "??$make_shared_with_deleter@VSkillTargetCharaSelChoice_Data@ope@ui@app@@@TPL@@YIV?$shared_ptr@VSkillTargetCharaSelChoice_Data@ope@ui@app@@U?$deleter_for_shared_ptr@VSkillTargetCharaSelChoice_Data@ope@ui@app@@@TPL@@@std@@XZ"
type = "void *"

[header]
name = "??$make_shared_with_deleter@VSkillTargetCharaSelChoice_Data@ope@ui@app@@@TPL@@YIV?$shared_ptr@VSkillTargetCharaSelChoice_Data@ope@ui@app@@U?$deleter_for_shared_ptr@VSkillTargetCharaSelChoice_Data@ope@ui@app@@@TPL@@@std@@XZ"
addr = 0x4b2010
type = "void *"

[header.args]
