last_change = 2025-10-28T01:57:08.273140Z
addr = 0x4c6130
size = 0x5
name = "j_??0?$optional@Vany@std@@@std@@QEAI@AEBV01@@Z"
type = "std::optional<std::any> *"

[header]
name = "j_??0?$optional@Vany@std@@@std@@QEAI@AEBV01@@Z"
addr = 0x4c6130
type = "std::optional<std::any> *"

[header.args]
