last_change = 2025-10-28T01:57:08.273140Z
addr = 0x4f9cf0
size = 0xbd
name = "??$make_shared_with_deleter@VAcademiaClassSelectChoice_Data@ope@ui@app@@@TPL@@YIV?$shared_ptr@VAcademiaClassSelectChoice_Data@ope@ui@app@@U?$deleter_for_shared_ptr@VAcademiaClassSelectChoice_Data@ope@ui@app@@@TPL@@@std@@XZ"
type = "void *"

[header]
name = "??$make_shared_with_deleter@VAcademiaClassSelectChoice_Data@ope@ui@app@@@TPL@@YIV?$shared_ptr@VAcademiaClassSelectChoice_Data@ope@ui@app@@U?$deleter_for_shared_ptr@VAcademiaClassSelectChoice_Data@ope@ui@app@@@TPL@@@std@@XZ"
addr = 0x4f9cf0
type = "void *"

[header.args]
