last_change = 2025-10-28T01:57:08.274141Z
addr = 0x6bfe90
size = 0x5
name = "??1?$StlVector@PEAUMaskBoxParam@fldMapIcon@fld@app@@@TPL@@QEAI@XZ"
type = "void *"

[header]
name = "??1?$StlVector@PEAUMaskBoxParam@fldMapIcon@fld@app@@@TPL@@QEAI@XZ"
addr = 0x6bfe90
type = "void *"

[header.args]
