last_change = 2025-10-28T01:57:08.274141Z
addr = 0x6b4790
size = 0x5
name = "j_??0fldGallicaTalk@fld@app@@QAI@XZ"
type = "void *"

[header]
name = "j_??0fldGallicaTalk@fld@app@@QAI@XZ"
addr = 0x6b4790
type = "void *"

[header.args]
