last_change = 2025-10-28T01:57:08.274141Z
addr = 0x711a80
size = 0x5
name = "j_??0fldMeshList@fld@app@@QEAI@XZ"
type = "void *"

[header]
name = "j_??0fldMeshList@fld@app@@QEAI@XZ"
addr = 0x711a80
type = "void *"

[header.args]
