last_change = 2025-10-28T01:57:08.274141Z
addr = 0x7b2ea0
size = 0x7
name = "?GetSystemLanguage@app@@YIW4AppLang@1@XZ"
type = "app::AppLang"

[header]
name = "?GetSystemLanguage@app@@YIW4AppLang@1@XZ"
addr = 0x7b2ea0
type = "app::AppLang"

[header.args]
