last_change = 2025-10-28T01:57:08.274642Z
addr = 0x839ad0
size = 0x28
name = "??0resrcBgData_mission_pos@resrc@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0resrcBgData_mission_pos@resrc@app@@QEAI@XZ"
addr = 0x839ad0
type = "void *"

[header.args]
