last_change = 2025-10-29T02:14:22.284396Z
addr = 0x8cf440
size = 0x44
name = "?FldCameraPath_SetAutoChange@@QEAIXXZ"

[header]
name = "?FldCameraPath_SetAutoChange@@QEAIXXZ"
addr = 0x8cf440

[header.args]
