last_change = 2025-10-29T02:14:22.284396Z
addr = 0x8cfa90
size = 0x1a3
name = "?FldCameraSetToParam_AngleToTgt@@QEAIXXZ"

[header]
name = "?FldCameraSetToParam_AngleToTgt@@QEAIXXZ"
addr = 0x8cfa90

[header.args]
