last_change = 2025-10-29T02:14:22.284396Z
addr = 0x8ceaa0
size = 0x7a
name = "?FldBgObjGetResScrIDByResrcUid@@QEAIXXZ"

[header]
name = "?FldBgObjGetResScrIDByResrcUid@@QEAIXXZ"
addr = 0x8ceaa0

[header.args]
