last_change = 2025-10-29T02:14:22.284396Z
addr = 0x8cedb0
size = 0x70
name = "?FldCameraBoxSetIsActivated@@QEAIXXZ"

[header]
name = "?FldCameraBoxSetIsActivated@@QEAIXXZ"
addr = 0x8cedb0

[header.args]
