last_change = 2025-10-29T02:14:22.284396Z
addr = 0x8ce420
size = 0x156
name = "?FldBgDataIsContainLayoutName@@QEAIXXZ"

[header]
name = "?FldBgDataIsContainLayoutName@@QEAIXXZ"
addr = 0x8ce420

[header.args]
