last_change = 2025-10-29T02:14:22.284396Z
addr = 0x8ce580
size = 0x156
name = "?FldBgDataIsContainNodeName@@QEAIXXZ"

[header]
name = "?FldBgDataIsContainNodeName@@QEAIXXZ"
addr = 0x8ce580

[header.args]
