last_change = 2025-10-29T02:14:22.284396Z
addr = 0x8cec30
size = 0x43
name = "?FldCameraBoxAllSetWideMode@@QEAIXXZ"

[header]
name = "?FldCameraBoxAllSetWideMode@@QEAIXXZ"
addr = 0x8cec30

[header.args]
