last_change = 2025-10-29T02:14:22.284897Z
addr = 0x8d4e90
size = 0xa4
name = "?FldGatherGetUidByLayoutName@@QEAIXXZ"

[header]
name = "?FldGatherGetUidByLayoutName@@QEAIXXZ"
addr = 0x8d4e90

[header.args]
