last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8dfe50
size = 0x5
name = "?FldScriptEventAssistSetCameraType@@QEAIXXZ"

[header]
name = "?FldScriptEventAssistSetCameraType@@QEAIXXZ"
addr = 0x8dfe50

[header.args]
