last_change = 2025-10-29T02:14:22.284897Z
addr = 0x8d50d0
size = 0x3d
name = "?FldGayaHitUpdateTableData@@QEAIXXZ"

[header]
name = "?FldGayaHitUpdateTableData@@QEAIXXZ"
addr = 0x8d50d0

[header.args]
