last_change = 2025-10-29T02:14:22.285397Z
addr = 0x8dbbb0
size = 0x1f
name = "?FldPlayerIsAutoCtrl@@QEAIXXZ"
type = "bool"

[header]
name = "?FldPlayerIsAutoCtrl@@QEAIXXZ"
addr = 0x8dbbb0
type = "bool"

[header.args]
