last_change = 2025-10-29T02:14:22.285397Z
addr = 0x8db070
size = 0x3d
name = "?FldNpcSetSummaryOnByTable@@QEAIXXZ"

[header]
name = "?FldNpcSetSummaryOnByTable@@QEAIXXZ"
addr = 0x8db070

[header.args]
