last_change = 2025-10-29T02:14:22.284897Z
addr = 0x8d57a0
size = 0x3d
name = "?FldGmcGetExcelData_EnemyLayoutID@@QEAIXXZ"

[header]
name = "?FldGmcGetExcelData_EnemyLayoutID@@QEAIXXZ"
addr = 0x8d57a0

[header.args]
