last_change = 2025-10-29T02:14:22.285397Z
addr = 0x8dfab0
size = 0x99
name = "?FldPlayerWalkToFrontByHitCollis@@QEAIXXZ"

[header]
name = "?FldPlayerWalkToFrontByHitCollis@@QEAIXXZ"
addr = 0x8dfab0

[header.args]
