last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8dff40
size = 0x61
name = "?FldSetEnableBgDataNodeName@@QEAIXXZ"

[header]
name = "?FldSetEnableBgDataNodeName@@QEAIXXZ"
addr = 0x8dff40

[header.args]
