last_change = 2025-10-29T02:14:22.284396Z
addr = 0x8d12a0
size = 0x5
name = "?FldCreateEva@@QEAIXXZ"
type = "bool"

[header]
name = "?FldCreateEva@@QEAIXXZ"
addr = 0x8d12a0
type = "bool"

[header.args]
