last_change = 2025-10-29T02:14:22.285397Z
addr = 0x8dc800
size = 0x15
name = "?FldPlayerSetAction@@QEAIXXZ"
type = "void"

[header]
name = "?FldPlayerSetAction@@QEAIXXZ"
addr = 0x8dc800
type = "void"

[header.args]
