last_change = 2025-10-29T02:14:22.284897Z
addr = 0x8d6d00
size = 0x57
name = "?FldMemberAllSetAIState_Event@@QEAIXXZ"

[header]
name = "?FldMemberAllSetAIState_Event@@QEAIXXZ"
addr = 0x8d6d00

[header.args]
