last_change = 2025-10-29T02:14:22.285397Z
addr = 0x8d8fc0
size = 0x33
name = "?FldMsgReportDungeonScenario@@QEAIXXZ"

[header]
name = "?FldMsgReportDungeonScenario@@QEAIXXZ"
addr = 0x8d8fc0

[header.args]
