last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8dfcf0
size = 0x2e
name = "?FldSaveEntryGimmickDestination_Register@@QEAIXXZ"

[header]
name = "?FldSaveEntryGimmickDestination_Register@@QEAIXXZ"
addr = 0x8dfcf0

[header.args]
