last_change = 2025-10-29T02:14:22.285397Z
addr = 0x8dbbf0
size = 0x20
name = "?FldPlayerIsEndPreLoadEffect@@QEAIXXZ"

[header]
name = "?FldPlayerIsEndPreLoadEffect@@QEAIXXZ"
addr = 0x8dbbf0

[header.args]
