last_change = 2025-10-29T02:14:22.285397Z
addr = 0x8d8c80
size = 0x5
name = "?FldMorningQuestEventUnexecutedDaysCountReset@@QEAIXXZ"

[header]
name = "?FldMorningQuestEventUnexecutedDaysCountReset@@QEAIXXZ"
addr = 0x8d8c80

[header.args]
