last_change = 2025-10-29T02:14:22.284897Z
addr = 0x8d71f0
size = 0x8b
name = "?FldMemberGetUidByFollowIndex@@QEAIXXZ"

[header]
name = "?FldMemberGetUidByFollowIndex@@QEAIXXZ"
addr = 0x8d71f0

[header.args]
