last_change = 2025-10-29T02:14:22.284897Z
addr = 0x8d51b0
size = 0x56
name = "?FldGetEnableBgDataNodeName@@QEAIXXZ"

[header]
name = "?FldGetEnableBgDataNodeName@@QEAIXXZ"
addr = 0x8d51b0

[header.args]
