last_change = 2025-10-29T02:14:22.285397Z
addr = 0x8d9580
size = 0x61
name = "?FldNpcFollowerSummaryGetTalkFuncName@@QEAIXXZ"

[header]
name = "?FldNpcFollowerSummaryGetTalkFuncName@@QEAIXXZ"
addr = 0x8d9580

[header.args]
