last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8e00c0
size = 0x29
name = "?FldSoundEnvSetOverrideByCueID@@QEAIXXZ"

[header]
name = "?FldSoundEnvSetOverrideByCueID@@QEAIXXZ"
addr = 0x8e00c0

[header.args]
