last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8e0300
size = 0xa4
name = "?FldTboxGetUidByLayoutName@@QEAIXXZ"

[header]
name = "?FldTboxGetUidByLayoutName@@QEAIXXZ"
addr = 0x8e0300

[header.args]
