last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8fa470
size = 0xb
name = "?BtlLoadPrereadRandomDataByPack@@QEAIXXZ"

[header]
name = "?BtlLoadPrereadRandomDataByPack@@QEAIXXZ"
addr = 0x8fa470

[header.args]
