last_change = 2025-10-29T02:14:22.286398Z
addr = 0x8fdb80
size = 0x5
name = "?FldScriptFuncSetResult_Float@@QEAIXXZ"
type = "long long"

[header]
name = "?FldScriptFuncSetResult_Float@@QEAIXXZ"
addr = 0x8fdb80
type = "long long"

[header.args]
