last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8fb670
size = 0x17
name = "?DifficultySelectIsEnd@@QEAIXXZ"
type = "bool"

[header]
name = "?DifficultySelectIsEnd@@QEAIXXZ"
addr = 0x8fb670
type = "bool"

[header.args]
