last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8fb610
size = 0x3
name = "?DebugPadRumblePresetRuntimeTest@@QEAIXXZ"

[header]
name = "?DebugPadRumblePresetRuntimeTest@@QEAIXXZ"
addr = 0x8fb610

[header.args]
