last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8fa460
size = 0xb
name = "?BtlLoadPrereadMultiDataByPack@@QEAIXXZ"

[header]
name = "?BtlLoadPrereadMultiDataByPack@@QEAIXXZ"
addr = 0x8fa460

[header.args]
