last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8fa440
size = 0x5
name = "?BtlIsLoadedPrereadData@@QEAIXXZ"
type = "bool"

[header]
name = "?BtlIsLoadedPrereadData@@QEAIXXZ"
addr = 0x8fa440
type = "bool"

[header.args]
