last_change = 2025-10-29T02:14:22.286398Z
addr = 0x8fdb60
size = 0x5
name = "?FldScriptFuncGetArg_Int@@QEAIXXZ"
type = "long long"

[header]
name = "?FldScriptFuncGetArg_Int@@QEAIXXZ"
addr = 0x8fdb60
type = "long long"

[header.args]
