last_change = 2025-10-29T02:14:22.286398Z
addr = 0x8fe2b0
size = 0xc
name = "?GetCalendarRegion@@QEAIXXZ"
type = "SQInteger"

[header]
name = "?GetCalendarRegion@@QEAIXXZ"
addr = 0x8fe2b0
type = "SQInteger"

[header.args]
