last_change = 2025-10-29T02:14:22.286398Z
addr = 0x8fe060
size = 0x3
name = "?Food_ActivateEffect@@QEAIXXZ"
type = "void"

[header]
name = "?Food_ActivateEffect@@QEAIXXZ"
addr = 0x8fe060
type = "void"

[header.args]
