last_change = 2025-10-29T02:14:22.285898Z
addr = 0x8fc790
size = 0x5
name = "?EventWipeIsOutEnd@@QEAIXXZ"
type = "bool"

[header]
name = "?EventWipeIsOutEnd@@QEAIXXZ"
addr = 0x8fc790
type = "bool"

[header.args]
