last_change = 2025-10-29T02:14:22.286899Z
addr = 0x904540
size = 0x5
name = "?Quest_GetNumSpecifiedDaysToLimit@@QEAIXXZ"

[header]
name = "?Quest_GetNumSpecifiedDaysToLimit@@QEAIXXZ"
addr = 0x904540

[header.args]
