last_change = 2025-10-29T02:14:22.286398Z
addr = 0x903320
size = 0x3f
name = "?MsgRequestSystemMessageID@@QEAIXXZ"

[header]
name = "?MsgRequestSystemMessageID@@QEAIXXZ"
addr = 0x903320

[header.args]
