last_change = 2025-10-29T02:14:22.286899Z
addr = 0x907890
size = 0x5
name = "?SortieMapUI_GetFollowerHelpID@@QEAIXXZ"

[header]
name = "?SortieMapUI_GetFollowerHelpID@@QEAIXXZ"
addr = 0x907890

[header.args]
