last_change = 2025-10-29T02:14:22.287399Z
addr = 0x908fc0
size = 0x17
name = "?Staffroll_IsReadyUI@@QEAIXXZ"
type = "bool"

[header]
name = "?Staffroll_IsReadyUI@@QEAIXXZ"
addr = 0x908fc0
type = "bool"

[header.args]
