last_change = 2025-10-29T02:14:22.286899Z
addr = 0x906ce0
size = 0x5
name = "?SeqExistEvent@@QEAIXXZ"
type = "bool"

[header]
name = "?SeqExistEvent@@QEAIXXZ"
addr = 0x906ce0
type = "bool"

[header.args]
