last_change = 2025-10-29T02:14:22.286899Z
addr = 0x905840
size = 0x15
name = "?SafeRoomMenuUI_GetResult@@QEAIXXZ"
type = "SQInteger"

[header]
name = "?SafeRoomMenuUI_GetResult@@QEAIXXZ"
addr = 0x905840
type = "SQInteger"

[header.args]
