last_change = 2025-10-29T02:14:22.287399Z
addr = 0x908d50
size = 0x15
name = "?SortieUI_GetResult@@QEAIXXZ"
type = "SQInteger"

[header]
name = "?SortieUI_GetResult@@QEAIXXZ"
addr = 0x908d50
type = "SQInteger"

[header.args]
