last_change = 2025-10-29T02:14:22.286899Z
addr = 0x906690
size = 0x5
name = "?Savedata_ScriptSaveExecute@@QEAIXXZ"

[header]
name = "?Savedata_ScriptSaveExecute@@QEAIXXZ"
addr = 0x906690

[header.args]
