last_change = 2025-10-29T02:14:22.287399Z
addr = 0x908fa0
size = 0x17
name = "?Staffroll_IsClosed@@QEAIXXZ"
type = "bool"

[header]
name = "?Staffroll_IsClosed@@QEAIXXZ"
addr = 0x908fa0
type = "bool"

[header.args]
