last_change = 2025-10-29T02:14:22.287399Z
addr = 0x9099f0
size = 0x17
name = "?WorldMapIsClosed@@QEAIXXZ"
type = "bool"

[header]
name = "?WorldMapIsClosed@@QEAIXXZ"
addr = 0x9099f0
type = "bool"

[header.args]
