last_change = 2025-10-29T02:14:22.286899Z
addr = 0x906b80
size = 0x5
name = "?SeqCallField_Eva_DungeonEvent@@QEAIXXZ"

[header]
name = "?SeqCallField_Eva_DungeonEvent@@QEAIXXZ"
addr = 0x906b80

[header.args]
