last_change = 2025-10-29T02:14:22.286899Z
addr = 0x908670
size = 0x51
name = "?SortieMapUI_Open_Intercity@@QEAIXXZ"

[header]
name = "?SortieMapUI_Open_Intercity@@QEAIXXZ"
addr = 0x908670

[header.args]
