last_change = 2025-10-29T02:14:22.286899Z
addr = 0x908070
size = 0x11
name = "?SortieMapUI_GetPointPositionID@@QEAIXXZ"
type = "SQInteger"

[header]
name = "?SortieMapUI_GetPointPositionID@@QEAIXXZ"
addr = 0x908070
type = "SQInteger"

[header.args]
