last_change = 2025-10-29T02:14:22.286899Z
addr = 0x9084c0
size = 0x2b
name = "?SortieMapUI_IsEndMoveAutoCursor@@QEAIXXZ"
type = "bool"

[header]
name = "?SortieMapUI_IsEndMoveAutoCursor@@QEAIXXZ"
addr = 0x9084c0
type = "bool"

[header.args]
