last_change = 2025-10-29T02:14:22.286899Z
addr = 0x905f80
size = 0x5
name = "?SaveData_LoadGameSequence@@QEAIXXZ"

[header]
name = "?SaveData_LoadGameSequence@@QEAIXXZ"
addr = 0x905f80

[header.args]
