last_change = 2025-10-29T02:14:22.286899Z
addr = 0x906d60
size = 0x15
name = "?SeqIdleField@@QEAIXXZ"
type = "bool"

[header]
name = "?SeqIdleField@@QEAIXXZ"
addr = 0x906d60
type = "bool"

[header.args]
