last_change = 2025-10-29T02:14:22.286899Z
addr = 0x907df0
size = 0x11
name = "?SortieMapUI_GetMapID@@QEAIXXZ"
type = "SQInteger"

[header]
name = "?SortieMapUI_GetMapID@@QEAIXXZ"
addr = 0x907df0
type = "SQInteger"

[header.args]
