last_change = 2025-10-29T02:14:22.286398Z
addr = 0x901b60
size = 0x17
name = "?IsHumanParamUPEnd@@QEAIXXZ"
type = "bool"

[header]
name = "?IsHumanParamUPEnd@@QEAIXXZ"
addr = 0x901b60
type = "bool"

[header.args]
