last_change = 2025-10-29T02:14:22.286899Z
addr = 0x9044a0
size = 0x2d
name = "?QuestUI_Open_Accept@@QEAIXXZ"
type = "void"

[header]
name = "?QuestUI_Open_Accept@@QEAIXXZ"
addr = 0x9044a0
type = "void"

[header.args]
