last_change = 2025-10-29T02:14:22.287399Z
addr = 0x9097e0
size = 0x24
name = "?WipePreRead@@QEAIXXZ"
type = "void"

[header]
name = "?WipePreRead@@QEAIXXZ"
addr = 0x9097e0
type = "void"

[header.args]
