last_change = 2025-10-28T01:57:08.274642Z
addr = 0x9af730
size = 0x43
name = "??0Gimmick@takeuchi@@QEAI@Uu32@@@Z"
type = "void *"

[header]
name = "??0Gimmick@takeuchi@@QEAI@Uu32@@@Z"
addr = 0x9af730
type = "void *"

[header.args]
