last_change = 2025-10-28T01:57:08.275142Z
addr = 0x9cf180
size = 0x5
name = "j_?_Integer_from_chars@std@@SIUfrom_chars_result@std@@QEBDQEBDAEAHH@Z"
type = "std::from_chars_result *"

[header]
name = "j_?_Integer_from_chars@std@@SIUfrom_chars_result@std@@QEBDQEBDAEAHH@Z"
addr = 0x9cf180
type = "std::from_chars_result *"

[header.args]
