last_change = 2025-10-28T01:57:08.275142Z
addr = 0x9d0080
size = 0x5
name = "j_?HasLipPack@Manager@msg@app@@CI_NQEAUu8@@Uu32@@@Z"
type = "bool"

[header]
name = "j_?HasLipPack@Manager@msg@app@@CI_NQEAUu8@@Uu32@@@Z"
addr = 0x9d0080
type = "bool"

[header.args]
