last_change = 2025-10-28T01:57:08.275642Z
addr = 0xa8fb40
size = 0xd0
name = "??1Node@tree@academia@layout@ui@app@@QEAI@XZ"
type = "void"

[header]
name = "??1Node@tree@academia@layout@ui@app@@QEAI@XZ"
addr = 0xa8fb40
type = "void"

[header.args]
