last_change = 2025-10-28T01:57:08.275142Z
addr = 0xa89400
size = 0x39
name = "??0Bg@secret@academia@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Bg@secret@academia@layout@ui@app@@QEAI@XZ"
addr = 0xa89400
type = "void *"

[header.args]
