last_change = 2025-10-28T01:57:08.275142Z
addr = 0xa8ab10
size = 0x1eb
name = "??0Main@summoner@shop@academia@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Main@summoner@shop@academia@layout@ui@app@@QEAI@XZ"
addr = 0xa8ab10
type = "void *"

[header.args]
