last_change = 2025-10-28T01:57:08.275142Z
addr = 0xa89710
size = 0x33
name = "??0Confirm@summoner@shop@academia@layout@ui@app@@QAI@XZ"
type = "void *"

[header]
name = "??0Confirm@summoner@shop@academia@layout@ui@app@@QAI@XZ"
addr = 0xa89710
type = "void *"

[header.args]
