last_change = 2025-10-28T01:57:08.275142Z
addr = 0xa88c30
size = 0x7c
name = "??0?$StaticPaneArray@VPictPane@ui@app@@$08@ui@fw@@QEAI@XZ"
type = "void *"

[header]
name = "??0?$StaticPaneArray@VPictPane@ui@app@@$08@ui@fw@@QEAI@XZ"
addr = 0xa88c30
type = "void *"

[header.args]
