last_change = 2025-10-28T01:57:08.275642Z
addr = 0xac8b50
size = 0x5
name = "j_??0ListInfoItem@MessageLogLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "j_??0ListInfoItem@MessageLogLayout@ui@app@@QEAI@XZ"
addr = 0xac8b50
type = "void *"

[header.args]
