last_change = 2025-10-28T01:57:08.275642Z
addr = 0xad82b0
size = 0x5
name = "j_??1Line@synthese@command@layout@ui@app@@QEAI@XZ"
type = "void"

[header]
name = "j_??1Line@synthese@command@layout@ui@app@@QEAI@XZ"
addr = 0xad82b0
type = "void"

[header.args]
