last_change = 2025-10-28T01:57:08.275642Z
addr = 0xb15980
size = 0x281
name = "??0CharaLine@result@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0CharaLine@result@layout@ui@app@@QEAI@XZ"
addr = 0xb15980
type = "void *"

[header.args]
