last_change = 2025-10-28T01:57:08.276143Z
addr = 0xb21d10
size = 0x7c
name = "??1Week@calendar@layout@ui@app@@QAI@XZ"
type = "void *"

[header]
name = "??1Week@calendar@layout@ui@app@@QAI@XZ"
addr = 0xb21d10
type = "void *"

[header.args]
