last_change = 2025-10-28T01:57:08.276143Z
addr = 0xb3e240
size = 0x8ce
name = "??0CampEquipMainLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0CampEquipMainLayout@ui@app@@QEAI@XZ"
addr = 0xb3e240
type = "void *"

[header.args]
