last_change = 2025-10-28T01:57:08.276143Z
addr = 0xb3ec90
size = 0x43f
name = "??0ItemLine@equip@camp@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0ItemLine@equip@camp@layout@ui@app@@QEAI@XZ"
addr = 0xb3ec90
type = "void *"

[header.args]
