last_change = 2025-10-28T01:57:08.276143Z
addr = 0xb32d20
size = 0x15d
name = "??0Line@character_select@follower@camp@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Line@character_select@follower@camp@layout@ui@app@@QEAI@XZ"
addr = 0xb32d20
type = "void *"

[header.args]
