last_change = 2025-10-28T01:57:08.276143Z
addr = 0xb50f50
size = 0x44
name = "??0CampItemTargetClassSelectLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0CampItemTargetClassSelectLayout@ui@app@@QEAI@XZ"
addr = 0xb50f50
type = "void *"

[header.args]
