last_change = 2025-10-28T01:57:08.276143Z
addr = 0xb60660
size = 0x258
name = "??0Menu@menu@camp@layout@ui@app@@QEAI@XZ"
type = "void"

[header]
name = "??0Menu@menu@camp@layout@ui@app@@QEAI@XZ"
addr = 0xb60660
type = "void"

[header.args]
