last_change = 2025-10-28T01:57:08.276143Z
addr = 0xb61bf0
size = 0x2c
name = "??1PaintFocusBackPane@menu@camp@layout@ui@app@@QEAI@XZ"
type = "void"

[header]
name = "??1PaintFocusBackPane@menu@camp@layout@ui@app@@QEAI@XZ"
addr = 0xb61bf0
type = "void"

[header.args]
