last_change = 2025-10-28T01:57:08.276143Z
addr = 0xb767d0
size = 0x47
name = "??0QuestRankStar@quest@camp@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0QuestRankStar@quest@camp@layout@ui@app@@QEAI@XZ"
addr = 0xb767d0
type = "void *"

[header.args]
