last_change = 2025-10-28T01:57:08.276143Z
addr = 0xb8a4f0
size = 0x8d
name = "??0SkillLine@skill@camp@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0SkillLine@skill@camp@layout@ui@app@@QEAI@XZ"
addr = 0xb8a4f0
type = "void *"

[header.args]
