last_change = 2025-10-28T01:57:08.276143Z
addr = 0xb89e70
size = 0x44
name = "??0CampSkillTargetSelectLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0CampSkillTargetSelectLayout@ui@app@@QEAI@XZ"
addr = 0xb89e70
type = "void *"

[header.args]
