last_change = 2025-10-28T01:57:08.276643Z
addr = 0xba5030
size = 0x5
name = "j_??0CampInstantMenuLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "j_??0CampInstantMenuLayout@ui@app@@QEAI@XZ"
addr = 0xba5030
type = "void *"

[header.args]
