last_change = 2025-10-28T01:57:08.276643Z
addr = 0xbca550
size = 0x1c
name = "??0BufferTextureSetCallBackFunc@ui@app@@QAI@XZ"
type = "void *"

[header]
name = "??0BufferTextureSetCallBackFunc@ui@app@@QAI@XZ"
addr = 0xbca550
type = "void *"

[header.args]
