last_change = 2025-10-28T01:57:08.276643Z
addr = 0xbcb840
size = 0xb
name = "??1BufferTextureSetCallBackFunc@ui@app@@QAI@XZ"
type = "void **"

[header]
name = "??1BufferTextureSetCallBackFunc@ui@app@@QAI@XZ"
addr = 0xbcb840
type = "void **"

[header.args]
