last_change = 2025-10-28T01:57:08.276643Z
addr = 0xbcb090
size = 0x190
name = "??0MaterialLine@create_confirm@common@layout@ui@app@@QAI@XZ"
type = "void *"

[header]
name = "??0MaterialLine@create_confirm@common@layout@ui@app@@QAI@XZ"
addr = 0xbcb090
type = "void *"

[header.args]
