last_change = 2025-10-28T01:57:08.276643Z
addr = 0xc04d30
size = 0x38
name = "??1Line@audio@config@layout@ui@app@@QAI@XZ"
type = "void"

[header]
name = "??1Line@audio@config@layout@ui@app@@QAI@XZ"
addr = 0xc04d30
type = "void"

[header.args]
