last_change = 2025-10-28T01:57:08.276643Z
addr = 0xc042e0
size = 0x126
name = "??0Speed@config@layout@ui@app@@QAI@XZ"
type = "void *"

[header]
name = "??0Speed@config@layout@ui@app@@QAI@XZ"
addr = 0xc042e0
type = "void *"

[header.args]
