last_change = 2025-10-28T01:57:08.276643Z
addr = 0xc036e0
size = 0x73
name = "??0Brightness@config@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Brightness@config@layout@ui@app@@QEAI@XZ"
addr = 0xc036e0
type = "void *"

[header.args]
