last_change = 2025-10-28T01:57:08.276643Z
addr = 0xc24690
size = 0x27d
name = "??0BountyCounterLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0BountyCounterLayout@ui@app@@QEAI@XZ"
addr = 0xc24690
type = "void *"

[header.args]
