last_change = 2025-10-28T01:57:08.276643Z
addr = 0xc22db0
size = 0x9b
name = "??0ArenaStampLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0ArenaStampLayout@ui@app@@QEAI@XZ"
addr = 0xc22db0
type = "void *"

[header.args]
