last_change = 2025-10-28T01:57:08.276643Z
addr = 0xc2c3a0
size = 0x314
name = "??0Main@cook@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Main@cook@layout@ui@app@@QEAI@XZ"
addr = 0xc2c3a0
type = "void *"

[header.args]
