last_change = 2025-10-28T01:57:08.277144Z
addr = 0xc354f0
size = 0x58
name = "??0MenuLine@general@shop@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0MenuLine@general@shop@layout@ui@app@@QEAI@XZ"
addr = 0xc354f0
type = "void *"

[header.args]
