last_change = 2025-10-28T01:57:08.276643Z
addr = 0xc33340
size = 0x307
name = "??0Confirm@shop@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Confirm@shop@layout@ui@app@@QEAI@XZ"
addr = 0xc33340
type = "void *"

[header.args]
