last_change = 2025-10-28T01:57:08.276643Z
addr = 0xc33fc0
size = 0x2d5
name = "??0ListLine@shop@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0ListLine@shop@layout@ui@app@@QEAI@XZ"
addr = 0xc33fc0
type = "void *"

[header.args]
