last_change = 2025-10-28T01:57:08.277144Z
addr = 0xc35b40
size = 0xd4
name = "??0PopupCount@confirm@shop@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0PopupCount@confirm@shop@layout@ui@app@@QEAI@XZ"
addr = 0xc35b40
type = "void *"

[header.args]
