last_change = 2025-10-28T01:57:08.277144Z
addr = 0xc35440
size = 0x58
name = "??0MenuLine@armor@shop@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0MenuLine@armor@shop@layout@ui@app@@QEAI@XZ"
addr = 0xc35440
type = "void *"

[header.args]
