last_change = 2025-10-28T01:57:08.277144Z
addr = 0xc35c20
size = 0x95
name = "??0SaleIcon@shop@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0SaleIcon@shop@layout@ui@app@@QEAI@XZ"
addr = 0xc35c20
type = "void *"

[header.args]
