last_change = 2025-10-28T01:57:08.277144Z
addr = 0xc354a0
size = 0x4e
name = "??0MenuLine@base@shop@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0MenuLine@base@shop@layout@ui@app@@QEAI@XZ"
addr = 0xc354a0
type = "void *"

[header.args]
