last_change = 2025-10-28T01:57:08.277144Z
addr = 0xc6fc90
size = 0x1ef
name = "??0FieldSkillListLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0FieldSkillListLayout@ui@app@@QEAI@XZ"
addr = 0xc6fc90
type = "void *"

[header.args]
