last_change = 2025-10-28T01:57:08.277144Z
addr = 0xc71350
size = 0x5
name = "j_??1RewardFixLine@battle@layout@ui@app@@QEAI@XZ"
type = "void"

[header]
name = "j_??1RewardFixLine@battle@layout@ui@app@@QEAI@XZ"
addr = 0xc71350
type = "void"

[header.args]
