last_change = 2025-10-28T01:57:08.277144Z
addr = 0xc929a0
size = 0x2a1
name = "??0TraverlersVoiceLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0TraverlersVoiceLayout@ui@app@@QEAI@XZ"
addr = 0xc929a0
type = "void *"

[header.args]
