last_change = 2025-10-28T01:57:08.277644Z
addr = 0xcfb690
size = 0x78
name = "??0LineLayout@ChoicesLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0LineLayout@ChoicesLayout@ui@app@@QEAI@XZ"
addr = 0xcfb690
type = "void *"

[header.args]
