last_change = 2025-10-28T01:57:08.277644Z
addr = 0xd0dda0
size = 0xab
name = "??1Single@guide@layout@ui@app@@QEAI@XZ"
type = "void"

[header]
name = "??1Single@guide@layout@ui@app@@QEAI@XZ"
addr = 0xd0dda0
type = "void"

[header.args]
