last_change = 2025-10-28T01:57:08.277644Z
addr = 0xd1ee90
size = 0x2b
name = "??1StarSet@quest@layout@ui@app@@QEAI@XZ"
type = "void"

[header]
name = "??1StarSet@quest@layout@ui@app@@QEAI@XZ"
addr = 0xd1ee90
type = "void"

[header.args]
