last_change = 2025-10-28T01:57:08.277644Z
addr = 0xd1e1e0
size = 0x31c
name = "??0QuestNoticeLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0QuestNoticeLayout@ui@app@@QEAI@XZ"
addr = 0xd1e1e0
type = "void *"

[header.args]
