last_change = 2025-10-28T01:57:08.277644Z
addr = 0xd2d730
size = 0x1ea
name = "??0TitleVoiceSelectConfirmLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0TitleVoiceSelectConfirmLayout@ui@app@@QEAI@XZ"
addr = 0xd2d730
type = "void *"

[header.args]
