last_change = 2025-10-28T01:57:08.277644Z
addr = 0xd39d90
size = 0x1b
name = "??0Initilizer@SingleChoiceBase@ope@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Initilizer@SingleChoiceBase@ope@ui@app@@QEAI@XZ"
addr = 0xd39d90
type = "void *"

[header.args]
