last_change = 2025-10-28T01:57:08.277644Z
addr = 0xd4c700
size = 0x5
name = "j_??0YesNoChoiceSample@ope@ui@app@@QEAI@PEAX@Z"

[header]
name = "j_??0YesNoChoiceSample@ope@ui@app@@QEAI@PEAX@Z"
addr = 0xd4c700

[header.args]
