last_change = 2025-10-28T01:57:08.277644Z
addr = 0xd6b670
size = 0x30e
name = "??0BTL_ItemSelect@ope@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0BTL_ItemSelect@ope@ui@app@@QEAI@XZ"
addr = 0xd6b670
type = "void *"

[header.args]
