last_change = 2025-10-28T01:57:08.278144Z
addr = 0xd8f520
size = 0x1da
name = "??0?$ClassDetailBase@VResultSkillGetLayout@ui@app@@@ope@ui@app@@QEAI@PEAX@Z"
type = "void *"

[header]
name = "??0?$ClassDetailBase@VResultSkillGetLayout@ui@app@@@ope@ui@app@@QEAI@PEAX@Z"
addr = 0xd8f520
type = "void *"

[header.args]
