last_change = 2025-10-28T01:57:08.278144Z
addr = 0xd95710
size = 0x37
name = "??0?$SingleChoiceBase_WithNoNextLayout@VCalendarLayout@ui@app@@@ope@ui@app@@QEAI@PEAX@Z"
type = "void *"

[header]
name = "??0?$SingleChoiceBase_WithNoNextLayout@VCalendarLayout@ui@app@@@ope@ui@app@@QEAI@PEAX@Z"
addr = 0xd95710
type = "void *"

[header.args]
