last_change = 2025-10-28T01:57:08.278144Z
addr = 0xdbb0f0
size = 0x18d
name = "??0EquipMenuItemList@ope@ui@app@@QEAI@PEAX@Z"
type = "void *"

[header]
name = "??0EquipMenuItemList@ope@ui@app@@QEAI@PEAX@Z"
addr = 0xdbb0f0
type = "void *"

[header.args]
