last_change = 2025-10-28T01:57:08.278645Z
addr = 0xe0a8e0
size = 0x117
name = "??0EquipCharaSelChoice@ope@ui@app@@QEAI@PEAX@Z"
type = "void *"

[header]
name = "??0EquipCharaSelChoice@ope@ui@app@@QEAI@PEAX@Z"
addr = 0xe0a8e0
type = "void *"

[header.args]
