last_change = 2025-10-28T01:57:08.278645Z
addr = 0xe4b650
size = 0x46
name = "??0?$AcademiaShopConfirmChoiceBase@VAcademiaShopPersonaConfirmLayout@ui@app@@@ope@ui@app@@QEAI@PEAX@Z"
type = "void *"

[header]
name = "??0?$AcademiaShopConfirmChoiceBase@VAcademiaShopPersonaConfirmLayout@ui@app@@@ope@ui@app@@QEAI@PEAX@Z"
addr = 0xe4b650
type = "void *"

[header.args]
