last_change = 2025-10-28T01:57:08.278645Z
addr = 0xe563d0
size = 0xd3
name = "??0RecruitmentPlaceChoice@ope@ui@app@@QEAI@PEAX@Z"
type = "void *"

[header]
name = "??0RecruitmentPlaceChoice@ope@ui@app@@QEAI@PEAX@Z"
addr = 0xe563d0
type = "void *"

[header.args]
