last_change = 2025-10-28T01:57:08.278645Z
addr = 0xe63d90
size = 0x137
name = "??0PurchaseNumSelectChoice@ope@ui@app@@QEAI@PEAX@Z"
type = "void *"

[header]
name = "??0PurchaseNumSelectChoice@ope@ui@app@@QEAI@PEAX@Z"
addr = 0xe63d90
type = "void *"

[header.args]
