last_change = 2025-10-28T01:57:08.278645Z
addr = 0xe63b90
size = 0x14f
name = "??0ItemShopMenuChoice@ope@ui@app@@QEAI@PEAX@Z"
type = "void *"

[header]
name = "??0ItemShopMenuChoice@ope@ui@app@@QEAI@PEAX@Z"
addr = 0xe63b90
type = "void *"

[header.args]
