last_change = 2025-10-28T01:57:08.278645Z
addr = 0xe7f480
size = 0x5
name = "j_??0ChoiceData@ope@ui@app@@QEAI@XZ"

[header]
name = "j_??0ChoiceData@ope@ui@app@@QEAI@XZ"
addr = 0xe7f480

[header.args]
