last_change = 2025-10-28T01:57:08.279145Z
addr = 0xea0ce0
size = 0x21
name = "??0AnimatorContainerBase@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0AnimatorContainerBase@ui@app@@QEAI@XZ"
addr = 0xea0ce0
type = "void *"

[header.args]
