last_change = 2025-10-28T01:57:08.279145Z
addr = 0xea0d40
size = 0x5
name = "j_??0SeriesAnimatorBase@ui@app@@QAI@XZ"
type = "void *"

[header]
name = "j_??0SeriesAnimatorBase@ui@app@@QAI@XZ"
addr = 0xea0d40
type = "void *"

[header.args]
