last_change = 2025-10-30T01:28:09.541022Z
addr = 0xeb8a90
size = 0x10748
name = "FillsStringViewCollectionInSpriteStudioManager"
type = "unsigned long long *"

[header]
name = "FillsStringViewCollectionInSpriteStudioManager"
addr = 0xeb8a90
type = "unsigned long long *"

[header.args]
