last_change = 2025-10-28T01:57:08.279145Z
addr = 0xeefa20
size = 0x1b
name = "??0ModelInfo@UIModelManager@ui@app@@QAI@XZ"
type = "void *"

[header]
name = "??0ModelInfo@UIModelManager@ui@app@@QAI@XZ"
addr = 0xeefa20
type = "void *"

[header.args]
