last_change = 2025-10-28T01:57:08.279145Z
addr = 0xf44bd0
size = 0x1bb
name = "?Present@UUIC_Common_DifficultySelect@ui@app@@QEAIX_NW4Difficulty@3@@Z"
type = "void"

[header]
name = "?Present@UUIC_Common_DifficultySelect@ui@app@@QEAIX_NW4Difficulty@3@@Z"
addr = 0xf44bd0
type = "void"

[header.args]
