last_change = 2025-10-28T01:57:08.279145Z
addr = 0xf531c0
size = 0x250
name = "??0UUIC_Common_GameOver@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0UUIC_Common_GameOver@ui@app@@QEAI@XZ"
addr = 0xf531c0
type = "void *"

[header.args]
