last_change = 2025-10-28T01:57:08.279145Z
addr = 0xf8fc10
size = 0x140
name = "??0UUIC_Common_GamerTag@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0UUIC_Common_GamerTag@ui@app@@QEAI@XZ"
addr = 0xf8fc10
type = "void *"

[header.args]
