last_change = 2025-10-28T01:57:08.279645Z
addr = 0xfd4ca0
size = 0xa
name = "??0?$Flag@I@fw@@QEAI@XZ"
type = "void *"

[header]
name = "??0?$Flag@I@fw@@QEAI@XZ"
addr = 0xfd4ca0
type = "void *"

[header.args]
