last_change = 2025-10-28T01:57:08.280146Z
addr = 0x126c684
size = 0x5
name = "j_?criSvm_Execute@@SIXXZ_0"
type = "void"

[header]
name = "j_?criSvm_Execute@@SIXXZ_0"
addr = 0x126c684
type = "void"

[header.args]
