last_change = 2025-10-28T01:57:08.280146Z
addr = 0x13016dc
size = 0x13
name = "?criFsIo_CancelRead@@SIW5CriError@@PEBUCriFsIoInterface@@UCriFsFileHn@@@Z"
type = "CriError"

[header]
name = "?criFsIo_CancelRead@@SIW5CriError@@PEBUCriFsIoInterface@@UCriFsFileHn@@@Z"
addr = 0x13016dc
type = "CriError"

[header.args]
