last_change = 2025-10-28T01:57:08.280146Z
addr = 0x13ad821
size = 0x6
name = "j_?stricmp@shdfnd@physx@@YAHPEBD0@Z"
type = "int"

[header]
name = "j_?stricmp@shdfnd@physx@@YAHPEBD0@Z"
addr = 0x13ad821
type = "int"

[header.args]
