last_change = 2025-10-28T01:57:08.280146Z
addr = 0x13ad7fd
size = 0x6
name = "j_?getSize@MutexImpl@shdfnd@physx@@SAIXZ"
type = "unsigned int"

[header]
name = "j_?getSize@MutexImpl@shdfnd@physx@@SAIXZ"
addr = 0x13ad7fd
type = "unsigned int"

[header.args]
