last_change = 2025-10-28T01:57:08.280146Z
addr = 0x13ad809
size = 0x6
name = "j_?getCounterFrequency@Time@shdfnd@physx@@SA?AUCounterFrequencyToTensOfNanos@23@XZ"

[header]
name = "j_?getCounterFrequency@Time@shdfnd@physx@@SA?AUCounterFrequencyToTensOfNanos@23@XZ"
addr = 0x13ad809

[header.args]
