last_change = 2025-10-28T01:57:08.280146Z
addr = 0x13bf550
size = 0x5
name = "j_?sq_setnativeclosurename@@YIUSQRESULT@@UHSQUIRRELVM@@USQInteger@@PEBUSQChar@@@Z"

[header]
name = "j_?sq_setnativeclosurename@@YIUSQRESULT@@UHSQUIRRELVM@@USQInteger@@PEBUSQChar@@@Z"
addr = 0x13bf550

[header.args]
