last_change = 2025-10-28T01:57:08.280146Z
addr = 0x1404e50
size = 0x3f
name = "?Unknown11@LayoutBase@ui@fw@@QEAIXXZ"
type = "void"

[header]
name = "?Unknown11@LayoutBase@ui@fw@@QEAIXXZ"
addr = 0x1404e50
type = "void"

[header.args]
