last_change = 2025-10-28T01:57:08.280146Z
addr = 0x1404920
size = 0x5
name = "j_?RegisterDrawable@LayoutBase@ui@fw@@QEAIXPEAVDrawObject@23@@Z"
type = "void"

[header]
name = "j_?RegisterDrawable@LayoutBase@ui@fw@@QEAIXPEAVDrawObject@23@@Z"
addr = 0x1404920
type = "void"

[header.args]
