last_change = 2025-10-28T01:57:08.280647Z
addr = 0x140c2d0
size = 0xb
name = "??1DrawObject@ui@fw@@QEAI@XZ"
type = "void"

[header]
name = "??1DrawObject@ui@fw@@QEAI@XZ"
addr = 0x140c2d0
type = "void"

[header.args]
