last_change = 2025-10-28T01:57:08.280647Z
addr = 0x1425bb0
size = 0x2d
name = "??0TextureInfoBase@ui@fw@@QAI@XZ"
type = "fw::ui::TextureInfoBase *"

[header]
name = "??0TextureInfoBase@ui@fw@@QAI@XZ"
addr = 0x1425bb0
type = "fw::ui::TextureInfoBase *"

[header.args]
