last_change = 2025-10-28T01:57:08.280647Z
addr = 0x1452450
size = 0x5
name = "j_?PrintObjVal@SQVM@@QEAIPEAUSQString@@PEBUSQObjectPtr@@@Z"
type = "SQString *"

[header]
name = "j_?PrintObjVal@SQVM@@QEAIPEAUSQString@@PEBUSQObjectPtr@@@Z"
addr = 0x1452450
type = "SQString *"

[header.args]
