last_change = 2025-10-28T01:57:08.280647Z
addr = 0x1479720
size = 0x5
name = "TODO_TPLAllocFunc2"
type = "void *"

[header]
name = "TODO_TPLAllocFunc2"
addr = 0x1479720
type = "void *"

[header.args]
