last_change = 2025-10-28T01:57:08.281147Z
addr = 0x14a392d
size = 0x6
name = "j_?_Throw_Cpp_error@std@@YAXH@Z"
type = "void"

[header]
name = "j_?_Throw_Cpp_error@std@@YAXH@Z"
addr = 0x14a392d
type = "void"

[header.args]
