last_change = 2025-10-28T01:57:08.281647Z
addr = 0x1779a50
size = 0x1e
name = "??__Fs_TexturePartPackRegistrations@TextureManager@ui@app@@YIXXZ"
type = "void"

[header]
name = "??__Fs_TexturePartPackRegistrations@TextureManager@ui@app@@YIXXZ"
addr = 0x1779a50
type = "void"

[header.args]
