last_change = 2025-10-28T01:57:08.281647Z
addr = 0x3b4f6a0
size = 0xb7
name = "??0Academia@dat@app@@QAI@XZ"
type = "void *"

[header]
name = "??0Academia@dat@app@@QAI@XZ"
addr = 0x3b4f6a0
type = "void *"

[header.args]
