last_change = 2025-10-28T01:57:08.281647Z
addr = 0x49548f0
size = 0x13e
name = "??0Mask@dat@app@@QAI@XZ"
type = "void *"

[header]
name = "??0Mask@dat@app@@QAI@XZ"
addr = 0x49548f0
type = "void *"

[header.args]
