last_change = 2025-10-28T01:57:08.282148Z
addr = 0x4e9a970
size = 0x2f0
name = "??0Tutorial@dat@app@@QAI@XZ"
type = "void *"

[header]
name = "??0Tutorial@dat@app@@QAI@XZ"
addr = 0x4e9a970
type = "void *"

[header.args]
