last_change = 2025-10-28T01:57:08.282148Z
addr = 0x6422660
size = 0x1dc
name = "??0evtPfxProcessor@evt@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0evtPfxProcessor@evt@app@@QEAI@XZ"
addr = 0x6422660
type = "void *"

[header.args]
