last_change = 2025-10-28T01:57:08.282148Z
addr = 0x7565d70
size = 0x2b
name = "??0fldMapLink@fld@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0fldMapLink@fld@app@@QEAI@XZ"
addr = 0x7565d70
type = "void *"

[header.args]
