last_change = 2025-10-28T01:57:08.282148Z
addr = 0x92d59a0
size = 0x2e3
name = "??0fldScene_CmdBattle@fld@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0fldScene_CmdBattle@fld@app@@QEAI@XZ"
addr = 0x92d59a0
type = "void *"

[header.args]
