last_change = 2025-10-28T01:57:08.282148Z
addr = 0xa81a290
size = 0x43
name = "??0fldGmcDoor@fld@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0fldGmcDoor@fld@app@@QEAI@XZ"
addr = 0xa81a290
type = "void *"

[header.args]
