last_change = 2025-10-28T01:57:08.282148Z
addr = 0xa971ae0
size = 0x98
name = "??0fldEnvBox@fld@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0fldEnvBox@fld@app@@QEAI@XZ"
addr = 0xa971ae0
type = "void *"

[header.args]
