last_change = 2025-10-28T01:57:08.282648Z
addr = 0xbc78100
size = 0x1e6
name = "??0fldEplList@fld@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0fldEplList@fld@app@@QEAI@XZ"
addr = 0xbc78100
type = "void *"

[header.args]
