last_change = 2025-10-28T01:57:08.282648Z
addr = 0xbfd7ee0
size = 0xe8
name = "??0Calendar@scheduler@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Calendar@scheduler@app@@QEAI@XZ"
addr = 0xbfd7ee0
type = "void *"

[header.args]
