last_change = 2025-10-28T01:57:08.282648Z
addr = 0xcca88b0
size = 0x7a
name = "??0?$StaticPaneArray@VTextPane@ui@app@@$00@ui@fw@@QAI@XZ"
type = "void *"

[header]
name = "??0?$StaticPaneArray@VTextPane@ui@app@@$00@ui@fw@@QAI@XZ"
addr = 0xcca88b0
type = "void *"

[header.args]
