last_change = 2025-10-28T01:57:08.282648Z
addr = 0xccb0550
size = 0x259
name = "??0PaintFocus@horizon@paint@common@layout@ui@app@@QAI@XZ"
type = "void *"

[header]
name = "??0PaintFocus@horizon@paint@common@layout@ui@app@@QAI@XZ"
addr = 0xccb0550
type = "void *"

[header.args]
