last_change = 2025-10-28T01:57:08.282648Z
addr = 0xd2749c0
size = 0x38
name = "??0resrcBgData_npc@resrc@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0resrcBgData_npc@resrc@app@@QEAI@XZ"
addr = 0xd2749c0
type = "void *"

[header.args]
