last_change = 2025-10-28T01:57:08.282648Z
addr = 0xf4ee7d0
size = 0x155
name = "??0?$_Matcher@Uconst_iterator@string@std@@DV?$regex_traits@D@std@@D@std@@QAIV?$_Matcher@Uconst_iterator@string@std@@DV?$regex_traits@D@std@@D@std@@PEADPEADV?$regex_traits@D@std@@V_Root_node@std@@IW4syntax_option_type@regex_constants@std@@W4match_flag_type@regex_constants@std@@@Z"
type = "std::_Matcher<std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>, char, std::regex_traits<char>, char> *"

[header]
name = "??0?$_Matcher@Uconst_iterator@string@std@@DV?$regex_traits@D@std@@D@std@@QAIV?$_Matcher@Uconst_iterator@string@std@@DV?$regex_traits@D@std@@D@std@@PEADPEADV?$regex_traits@D@std@@V_Root_node@std@@IW4syntax_option_type@regex_constants@std@@W4match_flag_type@regex_constants@std@@@Z"
addr = 0xf4ee7d0
type = "std::_Matcher<std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>, char, std::regex_traits<char>, char> *"

[header.args]
