last_change = 2025-10-28T01:57:08.282648Z
addr = 0xf9fbb50
size = 0xc0
name = "?PushElement@?$RingBuffer@VData@BackLog@msg@app@@$0BO@@fw@@QEAIXAEBVData@BackLog@msg@app@@@Z"
type = "void"

[header]
name = "?PushElement@?$RingBuffer@VData@BackLog@msg@app@@$0BO@@fw@@QEAIXAEBVData@BackLog@msg@app@@@Z"
addr = 0xf9fbb50
type = "void"

[header.args]
