last_change = 2025-10-28T01:57:08.282648Z
addr = 0x10ae3750
size = 0xb0
name = "??1ListInfoItem@MessageLogLayout@ui@app@@QEAI@XZ"
type = "void"

[header]
name = "??1ListInfoItem@MessageLogLayout@ui@app@@QEAI@XZ"
addr = 0x10ae3750
type = "void"

[header.args]
