last_change = 2025-10-28T01:57:08.283148Z
addr = 0x12112000
size = 0x283
name = "??0datConfig@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0datConfig@ui@app@@QEAI@XZ"
addr = 0x12112000
type = "void *"

[header.args]
