last_change = 2025-10-28T01:57:08.283148Z
addr = 0x12c905c0
size = 0x16a
name = "??0Main@story@system@camp@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Main@story@system@camp@layout@ui@app@@QEAI@XZ"
addr = 0x12c905c0
type = "void *"

[header.args]
