last_change = 2025-10-28T01:57:08.283148Z
addr = 0x1308cbc0
size = 0xc3
name = "??0KingLayout@press@common@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0KingLayout@press@common@layout@ui@app@@QEAI@XZ"
addr = 0x1308cbc0
type = "void *"

[header.args]
