last_change = 2025-10-28T01:57:08.283148Z
addr = 0x14f8aa90
size = 0x178
name = "??0Line@load@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Line@load@layout@ui@app@@QEAI@XZ"
addr = 0x14f8aa90
type = "void *"

[header.args]
