last_change = 2025-10-28T01:57:08.283148Z
addr = 0x1514dfd0
size = 0x30
name = "??0UnderFadeLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0UnderFadeLayout@ui@app@@QEAI@XZ"
addr = 0x1514dfd0
type = "void *"

[header.args]
