last_change = 2025-10-28T01:57:08.283649Z
addr = 0x152dc530
size = 0x111
name = "??0MagGetEffectLayout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0MagGetEffectLayout@ui@app@@QEAI@XZ"
addr = 0x152dc530
type = "void *"

[header.args]
