last_change = 2025-10-28T01:57:08.283649Z
addr = 0x15b201d0
size = 0x75
name = "??0Difference@money@layout@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0Difference@money@layout@ui@app@@QEAI@XZ"
addr = 0x15b201d0
type = "void *"

[header.args]
