last_change = 2025-10-28T01:57:08.283649Z
addr = 0x177c05a0
size = 0x17d
name = "??0ChoiceData@ope@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0ChoiceData@ope@ui@app@@QEAI@XZ"
addr = 0x177c05a0
type = "void *"

[header.args]
