last_change = 2025-10-28T01:57:08.283649Z
addr = 0x17aad380
size = 0x54
name = "??1UI_MessageLogListInfoItem@ui@app@@QEAI@XZ"
type = "void"

[header]
name = "??1UI_MessageLogListInfoItem@ui@app@@QEAI@XZ"
addr = 0x17aad380
type = "void"

[header.args]
