last_change = 2025-10-28T01:57:08.283649Z
addr = 0x193d2990
size = 0x195
name = "??0UUIC_Common_ExpUP@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0UUIC_Common_ExpUP@ui@app@@QEAI@XZ"
addr = 0x193d2990
type = "void *"

[header.args]
