last_change = 2025-10-28T01:57:08.284149Z
addr = 0x19eb84f0
size = 0x2a6
name = "??0UUIC_Common_Saving@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0UUIC_Common_Saving@ui@app@@QEAI@XZ"
addr = 0x19eb84f0
type = "void *"

[header.args]
