last_change = 2025-10-28T01:57:08.284149Z
addr = 0x1a8b57a0
size = 0x42
name = "??0UUIC_Field_LargeMap@ui@app@@QEAI@XZ"
type = "void *"

[header]
name = "??0UUIC_Field_LargeMap@ui@app@@QEAI@XZ"
addr = 0x1a8b57a0
type = "void *"

[header.args]
