last_change = 2025-10-28T01:57:08.284149Z
addr = 0x1ae02370
size = 0x89
name = "CreatesUUICPartsContext"
type = "void *"

[header]
name = "CreatesUUICPartsContext"
addr = 0x1ae02370
type = "void *"

[header.args]
