last_change = 2025-10-28T01:57:08.284149Z
addr = 0x1f944c83
size = 0x175
name = "?criFsBinder_GetFileSize@@SIW5CriError@@UCriFsBinderHn@@PEBUCriChar8@@PEAUCriUint64@@@Z"
type = "CriError"

[header]
name = "?criFsBinder_GetFileSize@@SIW5CriError@@UCriFsBinderHn@@PEBUCriChar8@@PEAUCriUint64@@@Z"
addr = 0x1f944c83
type = "CriError"

[header.args]
