last_change = 2025-10-28T01:57:08.284649Z
addr = 0x20595320
size = 0x10b
name = "PlaySpriteSeq"
type = "app::ui::SpriteStudioPane *"

[header]
name = "PlaySpriteSeq"
addr = 0x20595320
type = "app::ui::SpriteStudioPane *"

[header.args]
