last_change = 2025-10-28T01:57:08.284649Z
addr = 0x20ebb2e0
size = 0xd2
name = "?DecompressResource@ResourceManager@TPL@@YIXPEAVResource@2@@Z"
type = "void"

[header]
name = "?DecompressResource@ResourceManager@TPL@@YIXPEAVResource@2@@Z"
addr = 0x20ebb2e0
type = "void"

[header.args]
