last_change = 2025-10-28T01:57:08.284649Z
addr = 0x21262e70
size = 0x7e
name = "?InternalGetPackFileEntryFileName@Resource@TPL@@SIUStlString@2@UDataHandle@12@U32@Us32@@@Z"
type = "TPL::StlString *"

[header]
name = "?InternalGetPackFileEntryFileName@Resource@TPL@@SIUStlString@2@UDataHandle@12@U32@Us32@@@Z"
addr = 0x21262e70
type = "TPL::StlString *"

[header.args]
